# Generated by Django 3.1 on 2020-08-19 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20200819_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2020, 8, 19, 15, 25, 0, 675146)),
        ),
    ]
