# Generated by Django 3.1 on 2020-08-24 18:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_auto_20200819_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
