# Generated by Django 3.1 on 2020-08-14 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.IntegerField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Brand',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='qna',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'managed': True},
        ),
        migrations.CreateModel(
            name='ProductAttachFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(blank=True, null=True, upload_to='%Y/%m/%d', verbose_name='파일')),
                ('filename', models.CharField(max_length=64, null=True, verbose_name='첨부파일명')),
                ('content_type', models.CharField(max_length=128, null=True, verbose_name='MIME TYPE')),
                ('size', models.IntegerField(verbose_name='파일 크기')),
                ('Product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='shop.product', verbose_name='Post')),
            ],
        ),
    ]
