# Generated by Django 3.1 on 2020-09-03 11:29

from django.db import migrations, models

#
class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200903_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='p_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
